# ============================================================================
# Plain-Vivado batch build for the Arty A7 — no FuseSoC / Python needed.
#
#   Run from the REPO ROOT:
#     vivado -mode batch -source build_fpga.tcl
#   (or double-click build_fpga.bat)
#
# Produces build/fpga/top_artya7.bit with the demo program already inside
# the SRAM (sw/asm-demo/sram_init.vmem, generated by sw/asm-demo/assemble.py).
# ============================================================================

# Arty A7-100T. For the A7-35T use: xc7a35ticsg324-1L
set part xc7a100tcsg324-1

# Work from the repo root (directory of this script) so the relative
# $readmemh paths inside the RTL (boot.mem, sram vmem) resolve.
cd [file dirname [file normalize [info script]]]
file mkdir build/fpga

create_project -in_memory -part $part

# Same compile list as the xsim flow, minus the sim-only files
set f [open dv/xsim/filelist.f r]
while {[gets $f line] >= 0} {
    set line [string trim $line]
    if {$line eq "" || [string index $line 0] eq "#"} { continue }
    read_verilog -sv $line
}
close $f

# FPGA top level + clock generator (20 MHz PLL)
read_verilog -sv rtl/fpga/top_artya7.sv
read_verilog -sv vendor/lowrisc_ibex/shared/rtl/fpga/xilinx/clkgen_xil7series.sv

read_xdc data/pins_artya7.xdc

# FPGA_XILINX selects the BUFGCE clock gate in dv/xsim/prim_shims.sv and the
# BSCANE2-based JTAG tap in the debug module.
synth_design -top top_artya7 -part $part \
    -include_dirs {vendor/lowrisc_ip/ip/prim/rtl rtl/system vendor/lowrisc_ibex/vendor/lowrisc_ip/dv/sv/dv_utils} \
    -verilog_define FPGA_XILINX=1 \
    -generic SRAMInitFile=sw/asm-demo/sram_init.vmem

opt_design
place_design
route_design

report_timing_summary -file build/fpga/timing_summary.rpt
report_utilization    -file build/fpga/utilization.rpt

write_bitstream -force build/fpga/top_artya7.bit

puts "=============================================="
puts "  BUILD OK  ->  build/fpga/top_artya7.bit"
puts "  Program the board with: program_fpga.bat"
puts "=============================================="
